# =========================
# Mineroyale12111 Config
# =========================

game:
  min-players: 2
  max-players: 20
  countdown-seconds: 30
  initial-pvp-grace-seconds: 45
  show-player-locator-bar: true
  give-initial-compass: true
  hide-name-tags: true
  disable-advancement-announcements: true
  restrict-block-modification-outside-border: true

world:
  name: world

  # ランダムに選ぶボーダー中心の最大距離
  random-center-range: 2000

  # 初期ボーダーサイズ
  initial-border-size: 1000

spawn:
  # プレイヤー同士の最小スポーン距離
  min-distance: 50

border:
  warning-distance: 10
  warning-time: 5

  phases:
    - wait: 45
      duration: 240
      size: 600

    - wait: 30
      duration: 180
      size: 400

    - wait: 20
      duration: 120
      size: 200

    - wait: 15
      duration: 90
      size: 100

    - wait: 10
      duration: 60
      size: 50

  final-phase:
    enable-smooth-move: true
    move-range: 40
    move-duration-seconds: 20

  enhanced-damage:
    enabled: true
    base-damage: 1.0
    increase-per-second: 0.5
    max-damage: 10.0
