name: mineroyale
version: "${version}"
main: me.shirasemaru.mineroyale.Mineroyale
api-version: "${pluginApiVersion}"

commands:
  mr:
    description: MineRoyale 管理コマンド
    usage: /mr <start|stop|reload>
    permission: mineroyale.admin
  spec:
    description: 観戦先一覧を開く
    usage: /spec

permissions:
  mineroyale.admin:
    description: MineRoyale 管理者権限
    default: op
